language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
branches:
  only:
    - master
    - develop
install:
  - "pip install coverage"
script: nosetests tests --with-coverage --cover-package=dlxsudoku
