language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "3.5-dev"
  - "nightly"
  - pypy
matrix:
  allow_failures:
    - python: 2.6
    - python: "3.5-dev"
    - python: "nightly"
    - python: pypy
branches:
  only:
    - master
    - develop
install:
  - "pip install coverage"
script: nosetests tests --with-coverage --cover-package=dlxsudoku
