language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install python-coveralls"
  - "pip install -e ."
script: py.test tests/ --cov dlxsudoku --cov-report term-missing
after_success:
  - coveralls
